### ISSUE TITLE
Add BamQC from Qualimap to pipeline

### ISSUE THREAD

**Issue by tatumdmortimer** [tracysmith/RGAPepPipe#26]

**Comment by ONeillMB1** [comment]
In order to incorporate qualimap into the pipeline we need to disable the display forwarding. On SnpSnap & PepPop I have made the following modification to the qualimap script and tested it in screen (not on Condor):
line 42: modified to " java_options="-Djava.awt.headless=true -Xmx$JAVA_MEM_SIZE -XX:MaxPermSize=1024m"

Anytime the program is reinstalled this modification will need to be done.

**Comment by ONeillMB1** [comment]
Usage:
qualimap bamqc -bam <arg> -outfile <arg> -outformat <arg - pdf or html>

**Comment by tatumdmortimer** [comment]
Closed with commit 	59ee480
